@generated
{
  "aliases_explicit.py": [],
  "aliases_implicit.py": [
    "Line 81: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 112: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 117: Expected 1 errors"
  ],
  "aliases_newtype.py": [],
  "aliases_recursive.py": [
    "Line 19: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 30: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveTuple']`\"]",
    "Line 42: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveMapping']`\"]",
    "Line 58: Unexpected errors ['Expected a type form, got instance of `_SpecialForm`']",
    "Line 59: Unexpected errors [\"Can't apply arguments to non-class, got type[list[Unknown]]\"]",
    "Line 62: Unexpected errors [\"Can't apply arguments to non-class, got type[list[Unknown]]\"]",
    "Line 65: Unexpected errors ['Expected a type form, got instance of `_SpecialForm`']",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got type[list[Unknown]]\"]",
    "Line 68: Unexpected errors [\"Can't apply arguments to non-class, got type[list[Unknown]]\"]"
  ],
  "aliases_type_statement.py": [
    "Line 26: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Lines 51, 52: Expected error (tag 'TA14')",
    "Lines 88, 89: Expected error (tag 'RTA6+')"
  ],
  "aliases_typealiastype.py": [
    "Line 44: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 17: Unexpected errors ['Argument `tuple[type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 18: Unexpected errors ['Argument `tuple[type[TypeVar[S]], type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 19: Unexpected errors ['Argument `tuple[type[TypeVar[T]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 22: Unexpected errors [\"Expected a type form, got instance of `Literal['GoodAlias5[S, TStr, P]']`\"]",
    "Line 23: Unexpected errors ['Argument `tuple[type[TypeVar[S]], type[TypeVar[TStr]], type[ParamSpec[P]], type[TypeVarTuple[Ts]]]` is not assignable to parameter `type_params` with type `tuple[ParamSpec | TypeVar | TypeVarTuple, ...]` in function `typing.TypeAliasType.__new__`']",
    "Line 35: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 36: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 37: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 38: Unexpected errors ['Expected a type form, got instance of `GenericAlias`']",
    "Line 39: Unexpected errors ['Expected a type form, got instance of `GenericAlias`', 'Expected an iterable, got `type[tuple[int, str, int]]`']"
  ],
  "aliases_variance.py": [
    "Line 24: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 32: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "annotations_coroutines.py": [],
  "annotations_forward_refs.py": [
    "Line 22: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 87: Unexpected errors ['Expected a type form, got instance of `(self: Self@ClassD) -> None`']",
    "Line 96: Unexpected errors ['assert_type(Any, int) failed']"
  ],
  "annotations_generators.py": [
    "Line 87: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 190: Unexpected errors ['Expected to yield a value of type `int`, but a bare `yield` gives `None` instead']"
  ],
  "annotations_methods.py": [],
  "annotations_typeexpr.py": [],
  "callables_annotation.py": [
    "Line 156: Unexpected errors ['`Proto4[Ellipsis]` is not assignable to `Proto3`']",
    "Line 157: Unexpected errors ['`Proto7` is not assignable to `Proto6`']"
  ],
  "callables_kwargs.py": [
    "Line 111: Expected 1 errors",
    "Line 122: Expected 1 errors"
  ],
  "callables_protocol.py": [],
  "callables_subtyping.py": [],
  "classes_classvar.py": [],
  "classes_override.py": [
    "Lines 56, 64, 65: Expected error (tag 'method4')"
  ],
  "constructors_call_init.py": [
    "Line 107: Expected 1 errors",
    "Line 74: Unexpected errors ['assert_type(Class5[list[int]], Class5[set[str]]) failed', 'No matching overload found for function `Class5.__init__`\\n  Possible overloads:\\n  (value: int) -> None [closest match]\\n  (value: str) -> None\\n  (value: list[int]) -> None']",
    "Line 75: Unexpected errors ['assert_type(Class5[list[int]], Class5[float]) failed', 'No matching overload found for function `Class5.__init__`\\n  Possible overloads:\\n  (value: int) -> None [closest match]\\n  (value: str) -> None\\n  (value: list[int]) -> None']"
  ],
  "constructors_call_metaclass.py": [],
  "constructors_call_new.py": [],
  "constructors_call_type.py": [
    "Line 64: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 82: Expected 1 errors"
  ],
  "constructors_callable.py": [
    "Line 65: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 184: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 62: Unexpected errors ['Argument `type[Class3]` is not assignable to parameter `cb` with type `(*args: Unknown, **kwargs: Unknown) -> Self@Class3` in function `accepts_callable`']",
    "Line 64: Unexpected errors ['assert_type(Self, Class3) failed']",
    "Line 164: Unexpected errors ['assert_type(Class7[Any], Class7[int]) failed']",
    "Line 165: Unexpected errors ['assert_type(Class7[Any], Class7[str]) failed', \"Argument `Literal['']` is not assignable to parameter `x` with type `int`\"]",
    "Line 183: Unexpected errors ['assert_type(Self, Class8[str]) failed']",
    "Line 192: Unexpected errors ['Argument `type[Class9]` is not assignable to parameter `cb` with type `(ParamSpec(@_)) -> @_` in function `accepts_callable`']",
    "Line 194: Unexpected errors ['assert_type(Any, Class9) failed']"
  ],
  "constructors_consistency.py": [],
  "dataclasses_descriptors.py": [],
  "dataclasses_final.py": [
    "Line 35: Expected 1 errors"
  ],
  "dataclasses_frozen.py": [],
  "dataclasses_hash.py": [],
  "dataclasses_inheritance.py": [],
  "dataclasses_kwonly.py": [],
  "dataclasses_order.py": [],
  "dataclasses_postinit.py": [],
  "dataclasses_slots.py": [
    "Line 25: Expected 1 errors",
    "Line 38: Expected 1 errors"
  ],
  "dataclasses_transform_class.py": [],
  "dataclasses_transform_converter.py": [],
  "dataclasses_transform_field.py": [],
  "dataclasses_transform_func.py": [],
  "dataclasses_transform_meta.py": [],
  "dataclasses_usage.py": [],
  "directives_assert_type.py": [],
  "directives_cast.py": [],
  "directives_deprecated.py": [
    "Line 18: Expected 1 errors",
    "Line 25: Expected 1 errors"
  ],
  "directives_no_type_check.py": [],
  "directives_reveal_type.py": [],
  "directives_type_checking.py": [],
  "directives_type_ignore.py": [],
  "directives_type_ignore_file1.py": [],
  "directives_type_ignore_file2.py": [],
  "directives_version_platform.py": [],
  "enums_behaviors.py": [
    "Line 44: Expected 1 errors",
    "Line 19: Unexpected errors ['Type `type[Color]` is not iterable\\n  Argument `int` is not assignable to parameter `name` with type `str` in function `enum.EnumMeta.__getitem__`']",
    "Line 20: Unexpected errors ['assert_type(Any, Color) failed']"
  ],
  "enums_definition.py": [],
  "enums_expansion.py": [],
  "enums_member_names.py": [],
  "enums_member_values.py": [],
  "enums_members.py": [
    "Line 27: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet` is not visible on the class']",
    "Line 28: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet` is not visible on the class']",
    "Line 100: Unexpected errors ['assert_type(Literal[TrafficLight.AMBER], Literal[TrafficLight.YELLOW]) failed']"
  ],
  "exceptions_context_managers.py": [
    "Line 50: Unexpected errors ['assert_type(str, int | str) failed']",
    "Line 57: Unexpected errors ['assert_type(str, int | str) failed']"
  ],
  "generics_base_class.py": [
    "Line 68: Expected 1 errors",
    "Line 98: Expected 1 errors"
  ],
  "generics_basic.py": [
    "Line 49: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 34: Unexpected errors ['`+` is not supported between `AnyStr` and `AnyStr`\\n  Argument `AnyStr` is not assignable to parameter `self` with type `Self@bytes` in function `bytes.__add__`', '`+` is not supported between `AnyStr` and `AnyStr`\\n  No matching overload found for function `str.__add__`\\n  Possible overloads:\\n  (value: LiteralString, /) -> LiteralString [closest match]\\n  (value: str, /) -> str', 'Returned type `bytes | Unknown` is not assignable to declared return type `AnyStr`']",
    "Line 67: Unexpected errors ['assert_type(MyStr, str) failed']",
    "Line 68: Unexpected errors ['assert_type(MyStr, str) failed', 'Argument `str` is not assignable to parameter `y` with type `MyStr` in function `concat`']"
  ],
  "generics_defaults.py": [
    "Line 130: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 169: Unexpected errors ['assert_type([DefaultIntT](Foo7[DefaultIntT]) -> Foo7[DefaultIntT], (Foo7[int]) -> Foo7[int]) failed']",
    "Line 170: Unexpected errors ['assert_type(Any, int) failed', 'Instance-only attribute `attr` of class `Foo7` is not visible on the class']"
  ],
  "generics_defaults_referential.py": [
    "Line 66: Unexpected errors ['Expected default `TypeVar[X1]` of `Ok1` to be assignable to the upper bound of `float`']",
    "Line 67: Unexpected errors ['Expected default `TypeVar[X1]` of `AlsoOk1` to be assignable to the upper bound of `int`']",
    "Line 77: Unexpected errors ['Expected default `TypeVar[Y2]` of `AlsoOk2` to be one of the following constraints: `int`, `str`, `bool`']"
  ],
  "generics_defaults_specialization.py": [],
  "generics_paramspec_basic.py": [],
  "generics_paramspec_components.py": [
    "Line 30: Expected 1 errors"
  ],
  "generics_paramspec_semantics.py": [],
  "generics_paramspec_specialization.py": [],
  "generics_scoping.py": [
    "Line 50: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 87: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "generics_self_advanced.py": [
    "Line 38: Unexpected errors ['assert_type(ChildB, Self) failed']",
    "Line 43: Unexpected errors ['assert_type(Any, list[Self]) failed', 'Instance-only attribute `a` of class `ChildB` is not visible on the class']",
    "Line 44: Unexpected errors ['assert_type(Any, Self) failed', 'Instance-only attribute `a` of class `ChildB` is not visible on the class']",
    "Line 45: Unexpected errors ['assert_type(ChildB, Self) failed']"
  ],
  "generics_self_attributes.py": [
    "Line 32: Expected 1 errors"
  ],
  "generics_self_basic.py": [
    "Line 20: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 15: Unexpected errors ['Attribute `scale` is implicitly defined by assignment in method `set_scale`, which is not a constructor']"
  ],
  "generics_self_protocols.py": [
    "Line 58: Unexpected errors ['Argument `ReturnConcreteShape` is not assignable to parameter `shape` with type `ShapeProtocol` in function `accepts_shape`']"
  ],
  "generics_self_usage.py": [
    "Line 73: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 101: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 60: Unexpected errors ['TODO: Expr::attr_infer_for_type attribute base undefined for type: Self (trying to access x)']",
    "Line 63: Unexpected errors ['Argument `Self@HasNestedFunction` is not assignable to parameter `inner_self` with type `Self` in function `nested`']"
  ],
  "generics_syntax_compatibility.py": [],
  "generics_syntax_declarations.py": [],
  "generics_syntax_infer_variance.py": [],
  "generics_syntax_scoping.py": [
    "Line 92: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 66: Unexpected errors ['Found `S`, but it was not the global scope']",
    "Line 67: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 116: Unexpected errors ['assert_type(type[T], TypeVar) failed']"
  ],
  "generics_type_erasure.py": [],
  "generics_typevartuple_args.py": [],
  "generics_typevartuple_basic.py": [
    "Line 85: Unexpected errors ['Argument `tuple[float]` is not assignable to parameter `arg2` with type `tuple[int]` in function `func2`']"
  ],
  "generics_typevartuple_callable.py": [],
  "generics_typevartuple_concat.py": [
    "Line 56: Unexpected errors ['Returned type `tuple[*tuple[object | T, ...], object | T]` is not assignable to declared return type `tuple[*Ts, T]`']"
  ],
  "generics_typevartuple_overloads.py": [],
  "generics_typevartuple_specialization.py": [
    "Line 51: Unexpected errors ['assert_type(tuple[int, *tuple[Any, ...]], tuple[int]) failed']",
    "Line 94: Unexpected errors ['assert_type(tuple[float, *tuple[Any, ...]], tuple[float]) failed']",
    "Line 153: Unexpected errors ['Unpacked argument cannot be used for type parameter T1']",
    "Line 157: Unexpected errors ['assert_type(tuple[Any], tuple[*tuple[int, ...], int]) failed']"
  ],
  "generics_typevartuple_unpack.py": [],
  "generics_upper_bound.py": [
    "Line 51: Expected 1 errors"
  ],
  "generics_variance.py": [
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 163: Expected 1 errors",
    "Line 167: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Lines 125, 126: Expected error (tag 'CoContra_Child2')",
    "Lines 131, 132: Expected error (tag 'CoContra_Child3')",
    "Lines 141, 142: Expected error (tag 'CoContra_Child5')",
    "Lines 195, 196: Expected error (tag 'ContraToContraToContra_WithTA')"
  ],
  "generics_variance_inference.py": [],
  "historical_positional.py": [],
  "literals_interactions.py": [
    "Line 71: Unexpected errors ['`@` is not supported between `Matrix[Literal[2], Literal[3]]` and `Matrix[Literal[3], Literal[7]]`\\n  Argument `Matrix[Literal[3], Literal[7]]` is not assignable to parameter `other` with type `Matrix[Literal[3], int]` in function `Matrix.__matmul__`']",
    "Line 72: Unexpected errors ['assert_type(Matrix[Literal[2], int], Matrix[Literal[2], Literal[7]]) failed']"
  ],
  "literals_literalstring.py": [
    "Line 120: Expected 1 errors",
    "Line 52: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 111: Unexpected errors [\"assert_type(str, Literal['hello']) failed\"]"
  ],
  "literals_parameterizations.py": [],
  "literals_semantics.py": [],
  "namedtuples_define_class.py": [],
  "namedtuples_define_functional.py": [],
  "namedtuples_type_compat.py": [],
  "namedtuples_usage.py": [],
  "narrowing_typeguard.py": [],
  "narrowing_typeis.py": [],
  "overloads_basic.py": [],
  "overloads_consistency.py": [
    "Lines 25, 28: Expected error (tag 'return_type')",
    "Lines 41, 44: Expected error (tag 'parameter_type')"
  ],
  "overloads_definitions.py": [
    "Lines 71, 73, 78, 81: Expected error (tag 'func5')",
    "Lines 84, 86, 90, 94: Expected error (tag 'func6')",
    "Lines 121, 123, 127: Expected error (tag 'invalid_final')",
    "Lines 135, 136, 137, 141, 142: Expected error (tag 'invalid_final_2+')",
    "Lines 170, 175, 181, 183: Expected error (tag 'override-final')",
    "Lines 190, 191, 197, 198: Expected error (tag 'bad_override')",
    "Lines 220, 221, 222, 225, 226: Expected error (tag 'override_impl+')",
    "Line 49: Unexpected errors ['Overloaded function must have an implementation']"
  ],
  "overloads_evaluation.py": [
    "Line 105: Unexpected errors ['No matching overload found for function `example2`\\n  Possible overloads:\\n  (x: int, y: str, z: int) -> str [closest match]\\n  (x: int, y: int, z: int) -> int']",
    "Line 106: Unexpected errors ['assert_type(Any, int | str) failed']",
    "Line 134: Unexpected errors ['No matching overload found for function `expand_bool`\\n  Possible overloads:\\n  (x: Literal[False]) -> Literal[0] [closest match]\\n  (x: Literal[True]) -> Literal[1]']",
    "Line 135: Unexpected errors ['assert_type(Any, Literal[0, 1]) failed']",
    "Line 160: Unexpected errors ['No matching overload found for function `expand_enum`\\n  Possible overloads:\\n  (x: Literal[Color.RED]) -> Literal[0] [closest match]\\n  (x: Literal[Color.BLUE]) -> Literal[1]']",
    "Line 161: Unexpected errors ['assert_type(Any, Literal[0, 1]) failed']",
    "Line 180: Unexpected errors ['No matching overload found for function `expand_type_union`\\n  Possible overloads:\\n  (x: type[int]) -> int [closest match]\\n  (x: type[str]) -> str']",
    "Line 181: Unexpected errors ['assert_type(Any, int | str) failed']",
    "Line 204: Unexpected errors ['No matching overload found for function `expand_tuple`\\n  Possible overloads:\\n  (x: tuple[int, int]) -> int [closest match]\\n  (x: tuple[int, str]) -> str']",
    "Line 205: Unexpected errors ['assert_type(Any, int | str) failed']",
    "Line 234: Unexpected errors ['assert_type(str, int) failed']",
    "Line 264: Unexpected errors ['assert_type(list[int], Any) failed']",
    "Line 280: Unexpected errors ['assert_type(list[int], Any) failed']",
    "Line 345: Unexpected errors ['assert_type(list[int], Any) failed']"
  ],
  "protocols_class_objects.py": [
    "Line 29: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 104: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors",
    "Line 26: Unexpected errors ['Cannot instantiate `Proto` because it is a protocol']"
  ],
  "protocols_definition.py": [
    "Line 116: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 79: Unexpected errors ['`Concrete` is not assignable to `Template`']"
  ],
  "protocols_explicit.py": [
    "Line 27: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 165: Expected 1 errors"
  ],
  "protocols_generic.py": [
    "Line 144: Unexpected errors ['`ConcreteHasProperty1` is not assignable to `HasPropertyProto`']"
  ],
  "protocols_merging.py": [
    "Line 82: Expected 1 errors"
  ],
  "protocols_modules.py": [
    "Line 25: Unexpected errors ['`Module[_protocols_modules1]` is not assignable to `Options1`']"
  ],
  "protocols_recursive.py": [
    "Line 80: Unexpected errors ['Argument `ImplB` is not assignable to parameter `x` with type `ProtoA[Never, @_]` in function `func1`']",
    "Line 81: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "protocols_runtime_checkable.py": [
    "Line 88: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "protocols_self.py": [
    "Line 32: Unexpected errors ['`One` is not assignable to variable `c` with type `Copyable`']",
    "Line 33: Unexpected errors ['`Other` is not assignable to variable `c` with type `Copyable`']"
  ],
  "protocols_subtyping.py": [],
  "protocols_variance.py": [
    "Line 21: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 104: Expected 1 errors"
  ],
  "qualifiers_annotated.py": [
    "Line 76: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 93: Expected 1 errors"
  ],
  "qualifiers_final_annotation.py": [
    "Line 34: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 149: Expected 1 errors",
    "Line 152: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 166: Expected 1 errors",
    "Line 170: Expected 1 errors",
    "Line 131: Unexpected errors ['Expected first item to be a string literal', 'Expected first item to be a string literal']",
    "Line 133: Unexpected errors ['Unexpected keyword argument `x` in function `N.__new__`', 'Unexpected keyword argument `y` in function `N.__new__`']"
  ],
  "qualifiers_final_decorator.py": [
    "Lines 67, 68, 75: Expected error (tag 'method4')",
    "Lines 84, 85, 86: Expected error (tag 'Derived3-2')",
    "Lines 125, 126: Expected error (tag 'func')"
  ],
  "specialtypes_any.py": [],
  "specialtypes_never.py": [
    "Line 32: Unexpected errors [\"Returned type `Literal['whatever works']` is not assignable to declared return type `int`\"]"
  ],
  "specialtypes_none.py": [],
  "specialtypes_promotions.py": [],
  "specialtypes_type.py": [
    "Line 70: Expected 1 errors",
    "Line 84: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 99: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 100: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 102: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 106: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 110: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 139: Unexpected errors ['assert_type(type, type[Any]) failed']"
  ],
  "tuples_type_compat.py": [],
  "tuples_type_form.py": [],
  "tuples_unpacked.py": [],
  "typeddicts_alt_syntax.py": [],
  "typeddicts_class_syntax.py": [],
  "typeddicts_final.py": [],
  "typeddicts_inheritance.py": [
    "Line 65: Expected 1 errors"
  ],
  "typeddicts_operations.py": [],
  "typeddicts_readonly.py": [],
  "typeddicts_readonly_consistency.py": [],
  "typeddicts_readonly_inheritance.py": [
    "Line 98: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 132: Expected 1 errors"
  ],
  "typeddicts_readonly_kwargs.py": [],
  "typeddicts_readonly_update.py": [],
  "typeddicts_required.py": [
    "Line 62: Expected 1 errors",
    "Line 74: Unexpected errors [\"Expected a type form, got instance of `Literal['RecursiveMovie']`\"]"
  ],
  "typeddicts_type_consistency.py": [
    "Line 151: Unexpected errors [\"`dict[str, int]` is not assignable to TypedDict key `z` with type `Literal[''] | TypedDict[Inner3]`\"]"
  ],
  "typeddicts_usage.py": []
}